name: synheart_behavior
description: A lightweight, privacy-preserving mobile SDK that collects digital behavioral signals from smartphones.
version: 0.1.2
homepage: https://github.com/synheart-ai/synheart-behavior-dart
repository: https://github.com/synheart-ai/synheart-behavior-dart
issue_tracker: https://github.com/synheart-ai/synheart-behavior-dart/issues
license: Apache-2.0
topics:
  - behavior
  - digital-phenotyping
  - mobile-sensing
  - flutter
  - privacy

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.synheart.behavior
        pluginClass: SynheartBehaviorPlugin
      ios:
        pluginClass: SynheartBehaviorPlugin
  assets:
    - assets/models/linear_svc_model.onnx
    - assets/models/label_mapping.json
    - features.txt

